### ISSUE TITLE
kubernetes

### ISSUE THREAD

**Issue by zhanghaichang** [mritd/GitLabCI-TestProject#1]
哥们，有具体的kubernetes的demo没有,我看你这个是docker的。

**Comment by mritd** [comment]
@zhanghaichang https://mritd.me

**Comment by mritd** [comment]
@zhanghaichang 你是说 把 CI 都放到 k8s 里么？全部托管到 k8s  我没尝试过，感觉没太大必要

**Comment by zhanghaichang** [comment]
就是 Gitlab CI+Gitlab Runner +kubernetes, 一站式打包放在k8s里面运行。写k8s deploy和service yaml文件在项目工程里面。

**Comment by mritd** [comment]
目前我们还没这么做，因为考虑 CI build 可能会有很大压力，怕对节点造成影响，而且如果放进去还得处理 存储等问题，性能持久化都需要调整，我们目前的目标就是 集群内不跑有状态服务
